-- Vider la table post avant de la remplir
TRUNCATE TABLE post RESTART IDENTITY CASCADE;

-- Insérer 15 posts avec des images de test (images en base64)
INSERT INTO post (image, user_id) VALUES
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 1),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 2),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 3),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 4),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 5),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 1),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 2),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 3),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 4),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 5),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 1),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 2),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 3),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 4),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 5);