-- Insertion de 15 posts dans la table post

-- Vérifier d'abord que la table "post" existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'post') THEN
        RAISE EXCEPTION 'Table "post" does not exist.';
    END IF;
END $$;

-- Insérer 15 posts avec des images de test (images en base64)
INSERT INTO post (image, user_id) VALUES
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 1),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 2),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 3),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 4),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 5),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 1),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 2),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 3),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 4),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 5),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 1),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 2),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 3),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 4),
    (DECODE('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAHUlEQVR42mP8z/C/HwADgQH+sy6lGwAAAABJRU5ErkJggg==', 'base64'), 5);