version: "3.8"

networks:
  camagru:
    driver: bridge

services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - camagru

  frankenphp:
    build:
      context: ./frankenphp
      dockerfile: Dockerfile
    container_name: frankenphp
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./app:/var/www/html/app
      - ./frankenphp/Caddyfile:/etc/caddy/Caddyfile
      - ./frankenphp/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgresql
      - mailpit
    networks:
      - camagru
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  postgresql:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Europe/Zurich"
    networks:
      - camagru
